version: "3.9"
services:
  service:
    container_name: service
    image: service
    command: /service
    environment:
      - "REDIS_URL=redis:6379"
      - "TIMEOUT=3"
      - "SERVICE_ADDR=:9000"
      - "CHECKER_URL=http://checker:9000/check"
      - "YANDEX_FETCHERS=5"
    depends_on:
      - checker
      - redis
    ports:
      - "9000:9000"
  checker:
    container_name: checker
    image: checker
    command: /checker
    depends_on:
      - redis
    environment:
      - "REDIS_URL=redis:6379"
      - "TIMEOUT=3"
      - "CHECKER_ADDR=:9000"
      - "CHECKERS_COUNT=25"
      - "SERVICE_URL=http://service:9000/update"
  redis:
    container_name: redis
    image: redis
