version: "3.9"
services:
  service:
    container_name: service
    image: service
    command: /service
    environment:
      - "TIMEOUT=3"
      - "SERVICE_ADDR=:9000"
      - "CHECKER_URL=http://checker:9000/check"
      - "YANDEX_FETCHERS=5"
    ports:
      - "9000:9000"
  checker:
    container_name: checker
    image: checker
    command: /checker
    environment:
      - "CHECKER_ADDR=:9000"
      - "CHECKERS_COUNT=25"
      - "SERVICE_URL=http://service:9000/update"
