version: "3.9"
services:
  service:
    container_name: service
    image: service
    command: /service
    ports:
        - "9000:9000"
  checker:
    container_name: checker
    image: checker
    command: /checker

